### ISSUE TITLE
Issues about the results of the demo

### ISSUE THREAD

**Issue by JessieLi-RS** [ZJU-Robotics-Lab/DPCN#3]
Dear author,

Thank you for your amazing contribution. However, when I run the detect.py I found that the results are incorrect and far away from your demo. I have tried all the pretrained checkpoints and used the same src and template image. May I ask whether there is something I need to change to use your code?? Or could you please upload the test data in ./demo?

Best,
Jessie
![Figure_1](https://user-images.githubusercontent.com/73329378/125894643-a3ac2b74-30ed-48ab-9f63-0db65a217119.png)

**Comment by jessychen1016** [comment]
Hi Jessie,
As far as I can see in the picture you provided, you are using the same input image for the template and the source, which I believe is not the case for any pretrained we provided.

PS: for homogeneous image registration, you might want to comment out the UNETs in the detect_utils.py, so that the inputs are  directly fed to the registration pipeline without being processed by any networks.

Jessy

**Comment by JessieLi-RS** [comment]
Hi Jessy，

Thank you for your patience. I have commented out the UNETs and obtained reasonable results. May I ask is there something I need to modify when it comes to heterogeneous models and dynamic models?

Jessie

**Comment by jessychen1016** [comment]
if you are referring to the detect.py, then you are all set, just switch the pretrained model to the right one. If you are trying to train a model on your own dataset, please follow the groundtruth rule and create a csv file like those in the /data folder:)
